version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch-scm
    steps:
      - checkout
      - run: chmod +x start.sh
      - run: ./start.sh
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install SSH key
          command: |
            echo "${SSH_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
      - run:
          name: Deploy script
          command: |
            ssh -o StrictHostKeyChecking=no <your-username>@<your-server> 'bash -s' < script.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
